<?php

use App\Models\Location;
use Illuminate\Database\Seeder;

class LocationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Location::truncate();

        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94505, 'DISCOVERY BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94514, 'DISCOVERY BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94536, 'DISCOVERY BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94537, 'DISCOVERY BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94538, 'FREMONT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94539, 'FREMONT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94540, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94541, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94542, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94543, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94544, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94545, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94546, 'CASTRO VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94550, 'LIVERMORE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94551, 'LIVERMORE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94552, 'CASTRO VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94555, 'FREMONT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94557, 'HAYWARD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94560, 'NEWARK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94566, 'PLEASANTON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94568, 'DUBLIN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94577, 'SAN LEANDRO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94578, 'SAN LEANDRO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94579, 'SAN LEANDRO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94580, 'SAN LORENZO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94586, 'SUNOL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94587, 'UNION CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94588, 'PLEASANTON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94601, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94602, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94603, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94604, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94605, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94606, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94607, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94608, 'EMERYVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94609, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94610, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94611, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94612, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94613, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94614, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94615, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94617, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94618, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94619, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94620, 'PIEDMONT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94621, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94622, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94623, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94624, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94649, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94659, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94660, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94661, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94662, 'EMERYVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94666, 'OAKLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94701, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94702, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94703, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94704, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94705, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94706, 'ALBANY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94707, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94708, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94709, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94710, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94712, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94720, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94505, 'DISCOVERY BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94506, 'DANVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94507, 'ALAMO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94509, 'ANTIOCH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94511, 'BETHEL ISLAND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94513, 'BRENTWOOD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94514, 'BYRON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94516, 'CANYON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94517, 'CLAYTON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94518, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94519, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94520, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94521, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94522, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94523, 'PLEASANT HILL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94524, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94525, 'CROCKETT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94526, 'DANVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94527, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94528, 'DIABLO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94529, 'CONCORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94530, 'EL CERRITO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94531, 'ANTIOCH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94547, 'HERCULES, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94548, 'KNIGHTSEN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94549, 'LAFAYETTE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94551, 'LIVERMORE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94553, 'MARTINEZ, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94556, 'MORAGA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94561, 'OAKLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94563, 'ORINDA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94564, 'PINOLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94565, 'PITTSBURG, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94569, 'PORT COSTA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94570, 'MORAGA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94572, 'RODEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94575, 'MORAGA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94582, 'SAN RAMON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94583, 'SAN RAMON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94595, 'WALNUT CREEK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94596, 'WALNUT CREEK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94597, 'WALNUT CREEK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94598, 'WALNUT CREEK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94707, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94708, 'BERKELEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94801, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94802, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94803, 'EL SOBRANTE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94804, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94805, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94806, 'SAN PABLO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94807, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94808, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94820, 'EL SOBRANTE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94850, 'RICHMOND, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94022, 'LOS ALTOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94023, 'LOS ALTOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94024, 'LOS ALTOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94035, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94039, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94040, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94041, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94042, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94043, 'MOUNTAIN VIEW, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94085, 'SUNNYVALE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94086, 'SUNNYVALE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94087, 'SUNNYVALE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94088, 'SUNNYVALE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94089, 'SUNNYVALE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94301, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94302, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94303, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94304, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94305, 'STANFORD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94306, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94309, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94550, 'LIVERMORE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95002, 'ALVISO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95008, 'CAMPBELL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95009, 'CAMPBELL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95011, 'CAMPBELL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95013, 'COYOTE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95014, 'CUPERTINO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95015, 'CUPERTINO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95020, 'GILROY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95021, 'GILROY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95023, 'HOLLISTER, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95026, 'HOLY CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95030, 'LOS GATOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95031, 'LOS GATOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95032, 'LOS GATOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95033, 'LOS GATOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95035, 'MILPITAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95036, 'MILPITAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95037, 'MORGAN HILL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95038, 'MORGAN HILL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95042, 'NEW ALMADEN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95044, 'REDWOOD ESTATES, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95046, 'SAN MARTIN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95050, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95051, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95052, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95053, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95054, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95055, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95056, 'SANTA CLARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95070, 'SARATOGA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95071, 'SARATOGA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95076, 'WATSONVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95101, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95103, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95106, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95108, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95109, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95110, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95111, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95112, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95113, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95115, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95116, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95117, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95118, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95119, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95120, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95121, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95122, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95123, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95124, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95125, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95126, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95127, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95128, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95129, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95130, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95131, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95132, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95133, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95134, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95135, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95136, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95138, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95139, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95140, 'MOUNT HAMILTON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95141, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95148, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95150, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95151, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95152, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95153, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95154, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95155, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95156, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95157, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95158, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95159, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95160, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95161, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95164, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95170, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95172, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95173, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95190, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95191, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95192, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95193, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95194, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95196, 'SAN JOSE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94901, 'SAN RAFAEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94903, 'SAN RAFAEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94904, 'GREENBRAE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94912, 'SAN RAFAEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94913, 'SAN RAFAEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94914, 'KENTFIELD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94915, 'SAN RAFAEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94920, 'BELVEDERE TIBURON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94924, 'BOLINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94925, 'CORTE MADERA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94929, 'DILLON BEACH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94930, 'FAIRFAX, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94933, 'FOREST KNOLLS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94937, 'INVERNESS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94938, 'LAGUNITAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94939, 'LARKSPUR, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94940, 'MARSHALL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94941, 'MILL VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94942, 'MILL VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94945, 'NOVATO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94946, 'NICASIO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94947, 'NOVATO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94948, 'NOVATO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94949, 'NOVATO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94950, 'OLEMA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94956, 'POINT REYES STATION, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94957, 'ROSS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94960, 'SAN ANSELMO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94963, 'SAN GERONIMO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94964, 'SAN QUENTIN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94965, 'SAUSALITO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94966, 'SAUSALITO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94970, 'STINSON BEACH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94971, 'TOMALES, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94973, 'WOODACRE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94974, 'SAN QUENTIN, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94976, 'CORTE MADERA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94977, 'LARKSPUR, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94978, 'FAIRFAX, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94979, 'SAN ANSELMO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94998, 'NOVATO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94102, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94103, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94104, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94105, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94107, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94108, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94109, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94110, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94111, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94112, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94114, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94115, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94116, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94117, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94118, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94119, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94120, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94121, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94122, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94123, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94124, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94125, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94126, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94127, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94128, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94129, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94130, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94131, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94132, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94133, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94134, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94137, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94139, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94140, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94141, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94142, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94143, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94144, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94145, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94146, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94147, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94151, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94158, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94159, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94160, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94161, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94163, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94164, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94172, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94177, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94188, 'SAN FRANCISCO,CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94002, 'BELMONT, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94005, 'BRISBANE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94010, 'BURLINGAME, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94011, 'BURLINGAME, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94014, 'DALY CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94015, 'DALY CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94016, 'DALY CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94017, 'DALY CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94018, 'EL GRANADA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94019, 'HALF MOON BAY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94020, 'LA HONDA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94021, 'LOMA MAR, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94025, 'MENLO PARK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94026, 'MENLO PARK, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94027, 'ATHERTON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94028, 'PORTOLA VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94030, 'MILLBRAE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94037, 'MONTARA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94038, 'MOSS BEACH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94044, 'PACIFICA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94060, 'PESCADERO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94061, 'REDWOOD CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94062, 'REDWOOD CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94063, 'REDWOOD CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94064, 'REDWOOD CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94065, 'REDWOOD CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94066, 'SAN BRUNO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94070, 'SAN CARLOS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94074, 'SAN GREGORIO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94080, 'SOUTH SAN FRANCISCO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94083, 'SOUTH SAN FRANCISCO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94128, 'SAN FRANCISCO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94303, 'PALO ALTO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94401, 'SAN MATEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94402, 'SAN MATEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94403, 'SAN MATEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94404, 'SAN MATEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(94497, 'SAN MATEO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93426, 'BRADLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93450, 'SAN ARDO, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93451, 'SAN MIGUEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93901, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93902, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93905, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93906, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93907, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93908, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93912, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93915, 'SALINAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93920, 'BIG SUR, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93921, 'CARMEL BY THE SEA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93922, 'CARMEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93923, 'CARMEL, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93924, 'CARMEL VALLEY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93925, 'CHUALAR, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93926, 'GONZALES, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93927, 'GREENFIELD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93928, 'JOLON, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93930, 'KING CITY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93932, 'LOCKWOOD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93933, 'MARINA, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93940, 'MONTEREY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93942, 'MONTEREY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93943, 'MONTEREY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93944, 'MONTEREY, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93950, 'PACIFIC GROVE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93953, 'PEBBLE BEACH, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93954, 'SAN LUCAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93955, 'SEASIDE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93960, 'SOLEDAD, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(93962, 'SPRECKELS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95004, 'AROMAS, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95012, 'CASTROVILLE, CA', 4, 1);");
        \DB::statement("INSERT INTO `locations` (`zipcode`, `description`, `free_trial_period`, `is_active`) VALUES(95039, 'MOSS LANDING, CA', 4, 1);");
    }
}
