<?php

use App\Models\Skills;
use Illuminate\Database\Seeder;

class SkillsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Skills::query()->truncate();

        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(1, 0, 'General Clinical Training and Experience', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(2, 1, 'Alginate Impressions', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(3, 1, 'Amalgam Placement', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(4, 1, 'Antibiotic / Arestin Therapy', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(5, 1, 'Appointment Scheduling', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(6, 1, 'Bleaching Trays', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(7, 1, 'Bone Grafting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(8, 1, 'Charting ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(9, 1, 'Coronal Polishing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(10, 1, 'Cross-Trained Front & Back Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(11, 1, 'CPR', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(12, 1, 'Diode Laser Therapy', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(13, 1, 'Emergency Triage', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(14, 1, 'Fluoride Treatments', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(15, 1, 'General Special Needs Patients', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(16, 1, 'Hand-Scaling', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(17, 1, 'Hard Tissue Laser Procedures', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(18, 1, 'In-Office Whitening', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(19, 1, 'Insurance Claims Processing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(20, 1, 'Intraoral Camera', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(21, 1, 'Inventory Management', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(22, 1, 'Invisalign Experience', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(23, 1, 'IV Sedation', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(24, 1, 'Local Anesthesia Administration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(25, 1, 'Night Guards', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(26, 1, 'Nitrous Oxide Administration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(27, 1, 'Occlusal Adjustments', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(28, 1, 'Packing Cord', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(29, 1, 'Piezo Scaling', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(30, 1, 'Pouring / Trimming Stone Models', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(31, 1, 'Probing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(32, 1, 'Radiology', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(33, 1, 'Removable Dentures / Partials', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(34, 1, 'Rubber Dam Placement', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(35, 1, 'Sealant Placement', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(36, 1, 'Sleep Apnea Appliances', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(37, 1, 'Staining and Glazing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(38, 1, 'Sterilization', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(39, 1, 'Temporary Crowns', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(40, 1, 'Temporary Fillings', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(41, 1, 'Ultrasonic Scaling', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(42, 1, 'A-dec Trained', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(43, 1, 'Back Office Management', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(44, 1, 'Bookkeeping', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(45, 1, 'Botox Administration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(46, 1, 'Cad Cam Technology ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(47, 1, 'Composite Restorations', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(48, 1, 'Compressor Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(49, 1, 'Cone Beam 3D Imaging', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(50, 1, 'Crown Lengthening', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(51, 1, 'Defibrillator Administration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(52, 1, 'Dementia Patients ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(53, 1, 'Dental Unit Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(54, 1, 'Digital Impressions', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(55, 1, 'Digital Panoramic X- Ray ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(56, 1, 'Digital X-Ray Imaging', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(57, 1, 'Endodontic Treatment', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(58, 1, 'Equipment Maintenance Logs', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(59, 1, 'Fee Schedule Development', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(60, 1, 'Financial Planning ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(61, 1, 'General Marketing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(62, 1, 'General Practice Management Consulting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(63, 1, 'Geriatric Patients ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(64, 1, 'Gold Restorations', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(65, 1, 'Handpiece Maintenance ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(66, 1, 'House Calls', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(67, 1, 'HR Management', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(68, 1, 'Hygiene Program Development', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(69, 1, 'Implant Planning & Placement', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(70, 1, 'Implant Restoration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(71, 1, 'Infection Control', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(72, 1, 'Insurance / Claims Consulting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(73, 1, 'Insurance / Claims Processing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(74, 1, 'Medical Billing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(75, 1, 'Model Scanners', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(76, 1, 'MSDS Record Keeping', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(77, 1, 'Oral Cancer Screening', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(78, 1, 'Orthodontic Bracket Placement', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(79, 1, 'OSHA Office Compliance', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(80, 1, 'Patient Chair Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(81, 1, 'Patient Education', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(82, 1, 'Perio Surgery', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(83, 1, 'Pinhole Grafting Technique', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(84, 1, 'Practice Management Software ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(85, 1, 'Practice Management Software Training', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(86, 1, 'Provisionals', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(87, 1, 'Saliva Diagnostic Testing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(88, 1, 'Scaling & Root Planing (SRP)', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(89, 1, 'Social Media Marketing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(90, 1, 'Solea Laser Therapy', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(91, 1, 'Sports Mouthguards', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(92, 1, 'Sterilizer Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(93, 1, 'Stents ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(94, 1, 'Submitting & Updating Fee Schedules', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(95, 1, 'Supply Inventory Management', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(96, 1, 'Surgical Guides', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(97, 1, 'Systems Development ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(98, 1, 'Team Development ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(99, 1, 'Technology Diagnostics & Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(100, 1, 'TMJ Therapy', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(101, 1, 'Treatment Planning & Coordination', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(102, 1, 'Vacuum Repair ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(103, 1, 'X-Ray Calibration', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(104, 1, 'X-Ray Repair', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(105, 1, 'Other', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(106, 0, 'Practice Software Training & Experience ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(107, 106, 'Eaglesoft Front Office', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(108, 106, 'Eaglesoft Charting ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(109, 106, 'Dentrix Front Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(110, 106, 'Dentix Charting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(111, 106, 'Dentrix Ascend Cloud Front Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(112, 106, 'Dentrix Ascend Cloud Charting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(113, 106, 'EZ Dental Front office', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(114, 106, 'EZ Dental Charting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(115, 106, 'SoftDent Front Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(116, 106, 'SoftDent Charting ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(117, 106, 'Dolphin Orthodontic', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(118, 106, 'Open Dental Front Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(119, 106, 'Open Dental Charting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(120, 106, 'Curve Front Office', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(121, 106, 'Curve Charting', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(122, 106, 'EndoVision ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(123, 106, 'Ortho Trac Orthodontic', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(124, 106, 'Datacon Dental Front Office ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(125, 106, 'Datacon Dental Charting ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(126, 106, 'Lanmark360 Marketing ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(127, 106, 'Demandforce Marketing', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(128, 106, 'Zocdoc', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(129, 106, 'Revenue Well Marketing ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(130, 106, 'Caesy Patient Education Software', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(131, 106, 'Other', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(132, 0, 'Digital Dentistry Training & Experience', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(133, 132, '3M True Definition Digital Impression Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(134, 132, '3Shape TRIOS Digital Impression Scanner ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(135, 132, 'Carestream CS Digital Impression Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(136, 132, 'CEREC BlueCam  CAD-CAM ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(137, 132, 'CEREC OmniCam CAD CAM', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(138, 132, 'CEREC Ortho Digital Impression Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(139, 132, 'Dental Wings Digital Model Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(140, 132, 'iTero by Invisalign Digital Impression Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(141, 132, 'Lythos Digital Impression Scanner', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(142, 132, 'Planmeca PlanScan CAD CAM', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(143, 132, 'Other', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(144, 0, 'Digital Radiology Training & Experience', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(145, 144, 'CLIOS Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(146, 144, 'Dexis Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(147, 144, 'Gendex Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(148, 144, 'Gendex Phosphor Plate Digital X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(149, 144, 'MaxRay Handheld Portable X-Ray Unit', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(150, 144, 'Nomad Pro Handheld Portable X-Ray Unit', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(151, 144, 'Planmeca ProSensor Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(152, 144, 'Scanx Phosphor Plate Digital X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(153, 144, 'Schick Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(154, 144, 'Schick WiFi Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(155, 144, 'Suni Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(156, 144, 'Kodak Digital Sensors', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(157, 144, 'Gendex GXDP Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(158, 144, 'I-CAT Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(159, 144, 'Instrumentarium OP300 Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(160, 144, 'Newtom VGI - VGI evo or Giano Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(161, 144, 'Planmeca Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(162, 144, 'Sirona Galileos Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(163, 144, 'Sirona ORTHOPHOS Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(164, 144, 'Soredex CRANEX 3D Cone Beam X-Ray', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(165, 144, 'Other', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(166, 0, 'Languages', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(167, 166, 'English ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(168, 166, 'Spanish', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(169, 166, 'Farsi ', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(170, 166, 'Russian', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(171, 166, 'Cantonese', 1);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(172, 106, 'Mac Practice Front Office', 0);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(173, 106, 'Mac Practice Charting', 0);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(174, 1, 'Air Polishing Therapy (Hygiene)', 0);");
        \DB::statement("INSERT INTO `skills` (`id`, `parent_id`, `skill_name`, `is_active`) VALUES(175, 166, 'kl', 0);");
    }
}
